# Generated by Django 4.2.3 on 2023-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymLogistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
