# Generated by Django 4.2.3 on 2023-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymLogistic', '0002_alter_miembros_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
